#!/bin/bash
# fetch_download_urls.sh - Dynamic setup for JetBrains IDE download URLs

SCRIPT="./src/utils/get_version.py"
BASE_URL="https://download-cdn.jetbrains.com/"

# Fetch latest versions dynamically
VERSION_IIU=$(python3 "$SCRIPT" IIU)
VERSION_PCP=$(python3 "$SCRIPT" PCP)
VERSION_GO=$(python3 "$SCRIPT" GO)
VERSION_WS=$(python3 "$SCRIPT" WS)
VERSION_PS=$(python3 "$SCRIPT" PS)
VERSION_RD=$(python3 "$SCRIPT" RD)
VERSION_CL=$(python3 "$SCRIPT" CL)
VERSION_RM=$(python3 "$SCRIPT" RM)
VERSION_DG=$(python3 "$SCRIPT" DG)

# Base URLs
BASE_URL_INTELLIJ="${BASE_URL}idea/"
BASE_URL_PYCHARM="${BASE_URL}python/"
BASE_URL_GOLAND="${BASE_URL}go/"
BASE_URL_WEBSTORM="${BASE_URL}webstorm/"
BASE_URL_PHPSTORM="${BASE_URL}php/"
BASE_URL_RIDER="${BASE_URL}rider/"
BASE_URL_CLION="${BASE_URL}cpp/"
BASE_URL_RUBYMINE="${BASE_URL}ruby/"
BASE_URL_DATAGRIP="${BASE_URL}datagrip/"

# Construct download URLs
DOWNLOAD_URL_INTELLIJ="${BASE_URL_INTELLIJ}ideaIU-${VERSION_IIU}.tar.gz"
DOWNLOAD_URL_PYCHARM="${BASE_URL_PYCHARM}pycharm-professional-${VERSION_PCP}.tar.gz"
DOWNLOAD_URL_GOLAND="${BASE_URL_GOLAND}goland-${VERSION_GO}.tar.gz"
DOWNLOAD_URL_WEBSTORM="${BASE_URL_WEBSTORM}webstorm-${VERSION_WS}.tar.gz"
DOWNLOAD_URL_PHPSTORM="${BASE_URL_PHPSTORM}phpstorm-${VERSION_PS}.tar.gz"
DOWNLOAD_URL_RIDER="${BASE_URL_RIDER}rider-${VERSION_RD}.tar.gz"
DOWNLOAD_URL_CLION="${BASE_URL_CLION}clion-${VERSION_CL}.tar.gz"
DOWNLOAD_URL_RUBYMINE="${BASE_URL_RUBYMINE}rubymine-${VERSION_RM}.tar.gz"
DOWNLOAD_URL_DATAGRIP="${BASE_URL_DATAGRIP}datagrip-${VERSION_DG}.tar.gz"

# Export variables
export DOWNLOAD_URL_INTELLIJ DOWNLOAD_URL_PYCHARM DOWNLOAD_URL_GOLAND
export DOWNLOAD_URL_WEBSTORM DOWNLOAD_URL_PHPSTORM DOWNLOAD_URL_RIDER
export DOWNLOAD_URL_CLION DOWNLOAD_URL_RUBYMINE DOWNLOAD_URL_DATAGRIP

export VERSION_IIU VERSION_PCP VERSION_GO VERSION_WS VERSION_PS VERSION_RD VERSION_CL VERSION_RM VERSION_DG
export BASE_URL_INTELLIJ BASE_URL_PYCHARM BASE_URL_GOLAND BASE_URL_WEBSTORM BASE_URL_PHPSTORM BASE_URL_RIDER BASE_URL_CLION BASE_URL_RUBYMINE BASE_URL_DATAGRIP
